### PR TITLE
Wcs extensions

### PR DESCRIPTION
**Pull request by tastle**
@highsource, I've added all of the WCS extensions, except for wcseo (which I'd have to generate earth observation schemas and such, and I don't have need for at the moment).

Could you take a look at these, particularly the pom.xml files under the version directories that define the binding and dependencies?  I'm a bit rusty on those so maybe I have something in there that doesn't need to be there.

Everything generates okay, as far as I can tell.  I've taken care to ensure that only the correct class files are included in the jars and the JavaScript looks fine (thought I'm not using this for JSONIX at the moment).

If you accept by merging the pull, then I can try to make a release by following your notes.

### CODE REVIEW

**Comment by highsource** [comment]
I've accepted the merge but will go through the files. Please don't release yet, I'll give a signal.

**Comment by tastle** [comment]
:thumbsup:

**Comment by highsource** [comment]
I think it's done now. I've done some small fixes and JS/JSON Schema stuff.

**Comment by tastle** [comment]
Okay, I'll start the release process in a few moments for 2.5.3.  Wish me luck.

**Comment by highsource** [comment]
Oh, don't worry. What could just possibly go wrong? :-)

**Pull request merged**
